server:
   port: 80
   context-path: /
   session:
      timeout: -1
spring:
   profiles:
      active: dev
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_erp?characterEncoding=utf8
      username: root
      password: root
   jpa:
      hibernate.ddl-auto: update
      show-sql: true
   thymeleaf:
      cache: false
   jackson:
      date-format: